definitions:
  controller.Controller:
    type: object
  controller.MakeOrderInput:
    properties:
      businessName:
        type: string
      menu:
        items:
          properties:
            menuName:
              type: string
            number:
              type: integer
          type: object
        type: array
      orderer:
        type: string
    type: object
  controller.ModifyMenuInput:
    properties:
      category:
        type: string
      origin:
        type: string
      price:
        type: integer
      state:
        type: integer
      toUpdate:
        type: string
    type: object
  controller.ModifyOrderSwaggerInput:
    properties:
      menu:
        items:
          properties:
            menuName:
              type: string
            number:
              type: integer
          type: object
        type: array
      orderID:
        type: string
    type: object
  controller.NewMenuInput:
    properties:
      category:
        type: string
      name:
        type: string
      origin:
        type: string
      price:
        type: integer
    type: object
  controller.ReviewInput:
    properties:
      businessID:
        type: string
      content:
        type: string
      menuName:
        type: string
      orderID:
        type: string
      orderer:
        type: string
      score:
        type: number
    type: object
  controller.UpdateStateInput:
    properties:
      orderId:
        type: string
      state:
        type: integer
    type: object
info:
  contact: {}
paths:
  /menu/admin/modify:
    patch:
      consumes:
      - application/json
      parameters:
      - description: 사업체 ID
        in: header
        name: business_id
        required: true
        type: string
      - description: User input 바꿀 메뉴 이름 toUpdate로 추가, 바꿀내용만 작성
        in: body
        name: id
        required: true
        schema:
          $ref: '#/definitions/controller.ModifyMenuInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Controller'
      summary: call ModifyMenu, return ok by json.
  /menu/admin/new:
    post:
      consumes:
      - application/json
      parameters:
      - description: 사업체 ID
        in: header
        name: business_id
        required: true
        type: string
      - description: User input
        in: body
        name: id
        required: true
        schema:
          $ref: '#/definitions/controller.NewMenuInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Controller'
      summary: call NewMenu, return ok by json.
  /menu/list:
    get:
      consumes:
      - application/json
      parameters:
      - description: name
        in: query
        name: name
        required: true
        type: string
      - description: sort할 컬럼이름
        in: query
        name: sort
        required: true
        type: string
      - description: 'order= 1은 오름찬순 그 외 내림차순 '
        in: query
        name: order
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Controller'
      summary: call MenuList, return ok by json.
  /menu/list/review:
    get:
      consumes:
      - application/json
      parameters:
      - description: 가게 사업체 id
        in: query
        name: id
        required: true
        type: string
      - description: 메뉴 이름
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Controller'
      summary: call MenuReadReview, return ok by json.
  /order/admin/list:
    get:
      consumes:
      - application/json
      parameters:
      - description: 사업체 이름
        in: query
        name: businessname
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Controller'
      summary: call AdminListOrderController, return ok by json.
  /order/admin/update:
    patch:
      consumes:
      - application/json
      parameters:
      - description: '주문 번호, 상태 '
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/controller.UpdateStateInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Controller'
      summary: call UpdateState, return ok by json.
  /order/list:
    get:
      consumes:
      - application/json
      parameters:
      - description: 유저이름
        in: query
        name: name
        required: true
        type: string
      - description: 1은 현재 주문, 그 외 과거 주문
        in: query
        name: cur
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Controller'
      summary: call ListOrder, return ok by json.
  /order/make:
    post:
      consumes:
      - application/json
      parameters:
      - description: 주문자 이름, 주문 가게 이름, 메뉴 배열형태만 입력 ]
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/controller.MakeOrderInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Controller'
      summary: call MakeOrder, return ok by json.
  /order/modify:
    patch:
      consumes:
      - application/json
      parameters:
      - description: 수정할 주문 번호, 변경한 주문 메뉴 [{메뉴이름, 수량}]
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/controller.ModifyOrderSwaggerInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Controller'
      summary: call ModifyOrder, return ok by json.
  /review:
    post:
      consumes:
      - application/json
      parameters:
      - description: 리뷰
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/controller.ReviewInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Controller'
      summary: call MakeReview, return ok by json.
swagger: "2.0"
